Repository Sinchone/LastOne-FrontEnd, pull requests merged in 2023-03, with the labels that each got.

#5 [Setting]: react-query, recoil 초기 세팅
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: setting

#9 [#7]: style: 레이아웃, 헤더 구현
  src/components/Common/Header/index.tsx
  src/components/Common/Header/style.tsx
  src/components/Common/Layout/index.tsx
  src/components/Common/Layout/style.tsx
  src/components/Common/index.ts
  src/pages/_app.tsx
Labels: style

#10 [Feat]: Kakao login page 추가
  src/components/Common/Header/index.tsx
  src/components/Common/Header/style.tsx
  src/components/Common/Layout/index.tsx
  src/components/Common/Layout/style.tsx
  src/components/Common/index.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
Labels: feat

#16 [Feat]: Write page 컴포넌트 작업
  src/components/Common/Layout/index.tsx
  src/components/Write/Contents/index.tsx
  src/components/Write/Contents/style.tsx
  src/components/Write/Layout/index.tsx
  src/components/Write/Layout/style.tsx
  src/components/Write/Nav/index.tsx
  src/components/Write/Nav/style.tsx
  src/components/Write/index.ts
  src/pages/login/index.tsx
  src/pages/write/index.tsx
Labels: feat

#17 [Feat]: kakaoMap 추가
  src/components/Common/Layout/style.tsx
  src/components/Write/Contents/ContentsImg/index.tsx
  src/components/Write/Contents/ContentsMap/index.tsx
  src/components/Write/Contents/index.tsx
  src/components/Write/Contents/style.tsx
Labels: feat

#18 [Setting]: 스타일 (폰트, 컬러) 전역적으로 세팅
  .husky/pre-commit
  .husky/pre-push
  next.config.js
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globalStyles.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/typing/.empty
  src/typing/custom.d.ts
  src/typing/styled.d.ts
  yarn.lock
Labels: setting

#21 [Feat]: 헤더 및 배너 와이어프레임 구현
  package.json
  src/assets/.empty
  src/assets/icon/alarm.svg
  src/assets/icon/logo.svg
  src/assets/icon/user.svg
  src/components/Common/Header/index.tsx
  src/components/Common/Header/style.tsx
  src/components/Main/Banner/index.tsx
  src/components/Main/Banner/style.tsx
  src/components/Main/Contents/index.tsx
  src/components/Main/Contents/style.tsx
  src/components/Main/index.ts
  src/pages/index.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
  yarn.lock
Labels: feat

#22 [Feat]: 메인 페이지 퍼블리싱
  src/assets/icon/apply.svg
  src/assets/icon/chatting.svg
  src/assets/icon/home.svg
  src/assets/icon/mapmarker.svg
  src/assets/icon/partner.svg
  src/assets/icon/right-arrow.svg
  src/components/Common/Card/index.tsx
  src/components/Common/Card/style.tsx
  src/components/Common/Layout/style.tsx
  src/components/Common/Navigation/index.tsx
  src/components/Common/Navigation/style.tsx
  src/components/Common/index.ts
  src/components/Main/Contents/index.tsx
  src/components/Main/Contents/style.tsx
  src/pages/index.tsx
  src/styles/globalStyles.ts
Labels: feat

#24 [Feat]: 파트너 매칭 페이지 퍼블리싱
  src/assets/icon/bottom-arrow-small.svg
  src/assets/icon/bottom-arrow.svg
  src/assets/icon/search.svg
  src/components/Common/Card/index.tsx
  src/components/Common/Card/style.tsx
  src/components/Common/Navigation/index.tsx
  src/components/Main/Contents/index.tsx
  src/components/Matching/MatchingHeader/index.tsx
  src/components/Matching/MatchingHeader/style.tsx
  src/components/Matching/MatchingPosts/index.tsx
  src/components/Matching/MatchingPosts/style.tsx
  src/components/Matching/index.ts
  src/constants/.empty
  src/constants/index.ts
  src/constants/route.ts
  src/pages/matching/index.tsx
  src/styles/theme.ts
  tsconfig.path.json
Labels: feat, style

#26 [#15] fix : eslint 수정
  src/pages/login/index.tsx
Labels: fix

#27 [#15] fix : build 에러로 인한 수정
  package-lock.json
  src/components/Write/Contents/ContentsImg/index.tsx
  src/components/Write/Contents/Map/MapContainer/index.tsx
Labels: fix

#28 [Feat]: 글쓰기 페이지 기본 퍼블리싱
  src/assets/checkMarker.svg
  src/assets/icon/addImg.svg
  src/assets/icon/calendar.svg
  src/assets/icon/clock.svg
  src/assets/icon/left-arrow.svg
  src/assets/png/checkMarker.png
  src/assets/png/nomalMarker.png
  src/components/Upload/Contents/ContentsContainer/index.tsx
  src/components/Upload/Contents/ContentsContainer/style.tsx
  src/components/Upload/Contents/ContentsImg/index.tsx
  src/components/Upload/Contents/ContentsImg/style.tsx
  src/components/Upload/Contents/Map/KakaoMap/index.tsx
  src/components/Upload/Contents/Map/MapContainer/index.tsx
  src/components/Upload/Contents/Map/MapContainer/style.tsx
  src/components/Upload/Contents/Map/index.ts
  src/components/Upload/Contents/index.ts
  src/components/Upload/Layout/index.tsx
  src/components/Upload/Layout/style.tsx
  src/components/Upload/Nav/index.tsx
  src/components/Upload/Nav/style.tsx
  src/components/Upload/index.ts
  src/components/Write/Contents/ContentsContainer/style.tsx
  src/components/Write/Contents/ContentsImg/index.tsx
  src/components/Write/Contents/Map/MapContainer/index.tsx
  src/components/Write/Nav/index.tsx
  src/components/Write/index.ts
  src/pages/upload/index.tsx
  src/pages/write/index.tsx
Labels: feat

#29 [Feat] : 로그인페이지 기본 퍼블리싱 작업
  src/assets/icon/kakao.svg
  src/assets/icon/loginhome.svg
  src/assets/icon/loginlogo.svg
  src/components/Common/Layout/style.tsx
  src/components/Login/LoginLayout/index.tsx
  src/components/Login/LoginLayout/style.tsx
  src/components/Login/LoginNav/index.tsx
  src/components/Login/LoginNav/style.tsx
  src/components/Login/index.ts
  src/pages/login/index.tsx
  src/styles/globalStyles.ts
Labels: feat, style

#33 [Fix]: 모바일에서 푸터 깨지는 이슈 해결
  src/components/Common/Layout/style.tsx
  src/components/Common/Navigation/style.tsx
  src/components/Main/Contents/style.tsx
  src/components/Matching/MatchingPosts/style.tsx
Labels: fix, style

#35 [Modify]: 메인페이지, 파트너 매칭 페이지 디테일한 부분들 수정
  src/assets/icon/matching.svg
  src/assets/icon/profile.svg
  src/assets/icon/unclick-home.svg
  src/components/Common/Card/style.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Header/style.tsx
  src/components/Common/Layout/style.tsx
  src/components/Common/Navigation/index.tsx
  src/components/Common/Navigation/style.tsx
  src/components/Main/Contents/style.tsx
  src/components/Matching/MatchingHeader/index.tsx
  src/components/Matching/MatchingHeader/style.tsx
  src/constants/route.ts
  src/styles/theme.ts
  src/typing/styled.d.ts
Labels: refactor, style, modify

#36 [Feat]: 파트너 찾기 페이지 디테일한 부분들 구현
  src/assets/icon/bottom-arrow-white.svg
  src/assets/icon/bottomsheet.svg
  src/assets/icon/checkbox.svg
  src/assets/icon/close.svg
  src/assets/icon/plus.svg
  src/components/Common/BottomSheet/BottomSheetList/ExerciseArea/index.tsx
  src/components/Common/BottomSheet/BottomSheetList/ExerciseArea/style.tsx
  src/components/Common/BottomSheet/BottomSheetList/FitnessClub/index.tsx
  src/components/Common/BottomSheet/BottomSheetList/FitnessClub/style.tsx
  src/components/Common/BottomSheet/BottomSheetList/Gender/index.tsx
  src/components/Common/BottomSheet/BottomSheetList/Gender/style.tsx
  src/components/Common/BottomSheet/BottomSheetList/index.ts
  src/components/Common/BottomSheet/BottomSheetPortal/index.tsx
  src/components/Common/BottomSheet/index.tsx
  src/components/Common/BottomSheet/style.tsx
  src/components/Common/CheckBox/index.tsx
  src/components/Common/CheckBox/style.tsx
  src/components/Common/Header/style.tsx
  src/components/Common/Layout/style.tsx
  src/components/Common/index.ts
  src/components/Matching/MatchingFilter/ExerciseArea/index.tsx
  src/components/Matching/MatchingFilter/FiterContainer.tsx
  src/components/Matching/MatchingFilter/FitnessClub/index.tsx
  src/components/Matching/MatchingFilter/FitnessClub/style.tsx
  src/components/Matching/MatchingFilter/Gender/index.tsx
  src/components/Matching/MatchingFilter/index.ts
  src/components/Matching/MatchingFilter/style.tsx
  src/components/Matching/MatchingHeader/index.tsx
  src/components/Matching/MatchingHeader/style.tsx
  src/components/Matching/index.ts
  src/components/Search/Content/index.tsx
  src/components/Search/Content/style.tsx
  src/components/Search/Header/index.tsx
  src/components/Search/Header/style.tsx
  src/components/Search/History/index.tsx
  src/components/Search/History/style.tsx
  src/components/Search/Input/index.tsx
  src/components/Search/Input/style.tsx
  src/components/Search/index.ts
  src/constants/route.ts
  src/hooks/.empty
  src/hooks/common/index.ts
  src/hooks/common/useBottomSheet.ts
  src/pages/matching/index.tsx
  src/pages/search/index.tsx
  src/recoil/.empty
  src/recoil/bottomsheet/atom.ts
  src/recoil/bottomsheet/index.ts
  src/typing/bottomSheet.ts
  tsconfig.path.json
Labels: feat, style, modify
